### ISSUE TITLE
Error running ListLogger

### ISSUE THREAD

**Issue by jrlilly** [JetBrains/TeamCity.VSTest.TestAdapter#15] opened 2018-02-18 04:29 UTC
I've installed the TestAgent install of VS2017 and copied the DLLs to extension folder for 2017 and when running ListLoggers I'm receiving the following when using diag to get a log:

TpTrace Warning: 0 : 153304, 1, 2018/02/17, 23:04:12.428, 5918605317151, vstest.console.exe, TestPluginDiscoverer: Failed to get types from assembly 'TeamCity.VSTest.TestLogger, Version=1.0.7.140, Culture=neutral, PublicKeyToken=null'.  Skipping test extension scan for this assembly.  Error: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginDiscoverer.GetTestExtensionsFromAssembly[TPluginInfo,TExtension](Assembly assembly, Dictionary`2 pluginInfos)
TpTrace Warning: 0 : 153304, 1, 2018/02/17, 23:04:12.428, 5918605317476, vstest.console.exe, LoaderExceptions: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.CurrentDomainAssemblyResolve(Object sender, AssemblyResolveEventArgs args)
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformAssemblyResolver.AssemblyResolverEvent(Object sender, Object eventArgs)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)

**Comment by NikolayPianikov** [comment] 2018-03-16 18:21
@jrlilly which of the two folders did you copy?

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions`

or

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\TestPlatform\Extensions`

**Comment by NikolayPianikov** [comment] 2018-04-11 12:18
@jrlilly any updates?

**Comment by NikolayPianikov** [comment] 2018-05-22 11:50
@jrlilly I've closed this issue because of cannot reproduce it. Feel free to reopen it again if it is still reproducible

**Closed by NikolayPianikov** 2018-05-22 11:50 UTC
Labels: bug

**Comment by jrlilly** [comment] 2018-12-02 19:46
@NikolayPianikov re-opening, reproduction steps currently:

1. Take the 3 files in the zip and put into a folder
2. Open the command prompt in the folder
3. Run "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" /TestAdapterPath:. /ListLoggers /diag:log.txt

The log.txt will contain the error message in my first comment.
