### ISSUE TITLE
NUnit3TestAdapter 3.8.0

### ISSUE THREAD

**Issue by ecourtenay** [JetBrains/TeamCity.VSTest.TestAdapter#6] opened 2017-08-07 14:19 UTC
It appears that TeamCity.VSTest.TestAdapter isn't compatible with NUnit3TestAdapter - is this a known issue?

**Comment by NikolayPianikov** [comment] 2017-08-14 20:27
Look like it could be an issue. Is it possible to create simple project to reproduce? My 
[sample](https://github.com/JetBrains/TeamCity.VSTest.TestAdapter/files/1223362/a.zip) works fine

**Comment by NikolayPianikov** [comment] 2017-08-24 09:37
@ecourtenay do you still have this issue?

**Comment by NikolayPianikov** [comment] 2017-08-24 15:41
@ecourtenay I can't reproduce this issue. I've closed this issue, but please feel free to reopen it again if it still actual.

**Closed by NikolayPianikov** 2017-08-24 15:41 UTC
